sonar.host.url=http://localhost:9000
sonar.projectKey=1CArchitect

sonar.projectName=BSL

#Не забудьте что из Configuration.xml можно выцепить тег версия
sonar.projectVersion=1.0.0

#sonar.links.homepage=https://ourportal.mycompany.com/sharepoint-or-confluense-or-some-kb
#sonar.links.scm=https://ourgit.mycompany.com/ones-projects/ones-information-system-id
#sonar.links.issue=https://ourpmo.mycompany.com/jira-or-kaiten-or-sppr/<projects-id>


sonar.sources=./src/cf
#sonar.tests=./tests

sonar.inclusions=**/*.bsl, **/*.os
sonar.exclusions=/Reports/\u0420\u0435\u0433\u043b\u0430\u043c\u0435\u043d\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u043d*//*.*
sonar.sourceEncoding=UTF-8
#sonar.externalIssuesReportPaths=./out/acc-generic-issue.json
#D:/repo/kurs_devops_1/tools/acc-export/acc-generic-issue.json
#./tools/acc-export/acc-generic-issue.json
#sonar.bsl.languageserver.reportPaths=bsl-json.json
sonar.scm.exclusions.disabled=true
#sonar.scm.enabled=true
#sonar.scm.provider=git
